# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job:
  steps:
  - task: GitHubComment@0
    continueOnError: true
    inputs:
      gitHubConnection: 'Arsasana'
      repositoryName: 'Arsasana/azure-powershell'
      id: '1'
      comment: 'Commenting from pipeline'

- deployment: some_deployment
  environment: arsasanaEnv
  strategy: 
      runOnce:
        deploy:
          steps:
            - task: GitHubComment@0
              continueOnError: true
              inputs:
                gitHubConnection: 'Arsasana'
                repositoryName: 'Arsasana/azure-powershell'
                id: '1'
                comment: 'Commenting from pipeline'



